### ISSUE TITLE
Support setup.py

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#10]
Hi, @cocopon , are you going to use setuptools ?

**Comment by cocopon** [comment]
Yes.
I created PyPi account, and now I'm studying about package structure...
http://pythonhosted.org/an_example_pypi_project/setuptools.html

TODO:
- Convert README.markdown into reStructuredText
- Start version numbering

**Comment by Kuniwak** [comment]
OK, I see.
And then, we should be going to modify the directory structure for unit tests ( #4 ).
Please contact to me before this issue ( #10 ) was done.

**Comment by Kuniwak** [comment]
I merged #4, and now googkit breakaway from legacy code ;-)

It has some of file names change.
- `commands/` becomes `cmds/`
- `lib/command.py` becomes `lib/command_tree.py`

**Comment by cocopon** [comment]
OK, I see.

**Comment by cocopon** [comment]
Done.
But I have to do more things to make a complete package.
#18, #19
