### ISSUE TITLE
Doesn't work correctly when running in subdirectory

### ISSUE THREAD

**Issue by cocopon** [googkit/googkit#11]
Due to implementing the global config feature, googkit doesn't work when running in subdirectory.
We should set the current directory to the project home before executing commands.

**Comment by Kuniwak** [comment]
I see, but I'm resolving #4 now.
I going to resolve this problem when #4 was done.
Thanks!

**Comment by Kuniwak** [comment]
This problem was resolved on #4 .
So, I going to close this issue when #4 was merged to master.

**Comment by Kuniwak** [comment]
Done.
