### ISSUE TITLE
update_deps と apply_config の統合

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#2]
ClosureTools の仕組みを熟知していないと、`update_deps`と`apply_config`の違いがわからないのでは、と懸念しています。

`update_deps`と`apply_config`を統合した`update`を用意することで、もっと操作を簡単にできると思います。どうでしょうか？

**Comment by cocopon** [comment]
Added in branch 'subsubcommand' (e52428533abf12a16c299e454a9bda9a0a855757). Thanks!
