### ISSUE TITLE
Validating options

### ISSUE THREAD

**Issue by cocopon** [googkit/googkit#22]
For example, the following case should raise an error:

```
$ googkit build --berbose

[Error] Invalid option '--berbose'
```

**Comment by cocopon** [comment]
My plan:
- Each command has a list of acceptable options
  
  ``` python
  @classmethod
  def acceptable_options(cls):
      return ['--verbose']
  ```
- Validate options before running

**Comment by Kuniwak** [comment]
Good idea, @cocopon .

**Comment by cocopon** [comment]
Done. 8c7c3e06e5ba223e546051084395066f0b0c683d
