### ISSUE TITLE
`googkit _commands` should not print 'Complete.'

### ISSUE THREAD

**Issue by cocopon** [googkit/googkit#28]
The output will be used for shell completion, so this command should not print any extra messages.

**Comment by Kuniwak** [comment]
I decided to suppress messages from a command that finish instantly such as: ApplyConfig, UpdateDeps, Ready, Init.

**Comment by cocopon** [comment]
I see, but I think InitCommand needs to print the message.
Right now it doesn't print anything, so user can not know whether it succeeds or fails.

**Comment by cocopon** [comment]
For example, `git init` shows the following message:

```
Initialized empty Git repository in /Users/cocopon/Desktop/my_project/.git/
```

I think it's very important feedback for users.

Following commands don't print anything right now, so I want to add at least one line message as feedback:
- `googkit init`
- `googkit config apply`
- `googkit deps update`
- `googkit ready`

**Comment by Kuniwak** [comment]
OK, I gonna fix it.
