### ISSUE TITLE
Add `It works!` message to example

### ISSUE THREAD

**Issue by cocopon** [googkit/googkit#29]
Current example is hard to understand whether it works or not.
So I want to add `It works!` message to the example.

**Comment by Kuniwak** [comment]
What example is "it"? Please explain concretery more, @cocopon .

**Comment by cocopon** [comment]
Right now the example `foo.Example` shows:

if succeeded:

```
1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55
```

if failed:

```
(no output)
```

I think it's unkindness for users, especially newbies.

**Comment by Kuniwak** [comment]
OK, I see.

I think [Closure Demos](http://closure-library.googlecode.com/svn-history/r995/trunk/closure/goog/demos/index.html) are good examples.

**Comment by cocopon** [comment]
Looks nice. Thanks for helpful information :wink:
