### ISSUE TITLE
Should we use Travis CI?

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#31]
Should we use [Travis CI](https://travis-ci.org/)?
If we use Travis CI, then users can know test results.

**Comment by cocopon** [comment]
Yes. I'll add it later.

**Comment by Kuniwak** [comment]
I added `.travis.yml` and I confirmed that it works on my fork.

@cocopon, please activate [Github service hook](http://about.travis-ci.org/docs/user/getting-started/#Step-two%3A-Activate-GitHub-Service-Hook) on TravisCI (I cannot do this because it is not my repository).

**Comment by cocopon** [comment]
Thanks.
I activated it and added a badge in README (c85ca056dc1b63bcc3b6b44beff1bcb2b08f7a32).
