### ISSUE TITLE
Support to do lint all scripts by Closure Linter

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#33]
Support to do lint all scripts by [Closure Linter](https://developers.google.com/closure/utilities/).
At first, I gonna implement this command as a plugin.

Usage:

```
$ googkit lint
```

Config:

```
[linter]
zip_url=http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz
ignores=501,505
```

**Comment by cocopon** [comment]
Sounds good.
Can you implement this feature?
