### ISSUE TITLE
Support custom arguments for Closure Compiler

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#34]
We should support custom arguments for Closure Compiler such as `--jscomp_error=checkTypes` (makes type-safe), `--jscomp_error=visibility` (checks access violations).

Related article: [closure-compiler warnings](https://code.google.com/p/closure-compiler/wiki/Warnings)

**Comment by cocopon** [comment]
I can't imagine how to implement it yet.
Like this?

(in googkit.cfg)

```
[compiler]
jscomp_error=checkTypes,visibility,...
```

**Comment by Kuniwak** [comment]
I gonna add options such above:

```
[complier]
# 0: ignore, 1: warning, 2: error
check_types=2
visibility=0
...
```

**Comment by Kuniwak** [comment]
Now, googkit supports flagfiles for Closure Compiler and Closure Linter.
You can add custom argument in the flagfile specified by the `googkit.cfg`:

```
jscomp_error=checkTypes,visibility,...
```
