### ISSUE TITLE
Breakaway from legacy code

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#4]
We should start unit-testing.

**Comment by Kuniwak** [comment]
Hahaha, keeping unit tests to cross python version compatibility (2.7 and 3.3) is very very hard!

**Comment by Kuniwak** [comment]
This branch is ready to merge to master.
Please read the [help for unit-testing](https://github.com/cocopon/googkit/tree/issue4/test) and try unit-testing.

**Comment by cocopon** [comment]
Great work, thanks!
