### ISSUE TITLE
We need more docstrings

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#48]
We need more docstring for the Black-box testing.

**Comment by Kuniwak** [comment]
[docstring](https://github.com/googkit/googkit/tree/docstring) branch is ready but not merged yet.
@cocopon, please check docstrings and I gonna merge to master if it seems OK.

**Comment by cocopon** [comment]
@OrgaChem Please merge it, thanks!
And there is just one suggestion: How about adding `tag_format` to .watsonrc?

```
[tag_format]
TAG: COMMENT
```

This option will change `# [TODO] Foobar` to the same old format `# TODO: Foobar`.

https://github.com/nhmood/watson-ruby

**Comment by Kuniwak** [comment]
Merged (835426c7bf7aded486df454bf4accf811f505d8c).
