### ISSUE TITLE
Name of the entry point should be longer

### ISSUE THREAD

**Issue by cocopon** [googkit/googkit#50]
If an element that has id 'main' exists, it will conflict with the entry point 'main'. So we should change the name of the entry point more complex and longer.

**Comment by Kuniwak** [comment]
Hmm... it seems a difficult problem.

How about `googkit_main` or `googkit-main` instead of `main`?

**Comment by cocopon** [comment]
Sounds good. I'll change `main` to `googkit_main` later.

**Comment by Kuniwak** [comment]
done
