### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Kuniwak** [googkit/googkit#6]
I created a branch as [win_support](https://github.com/cocopon/googkit/tree/win_support) to support Windows.
This branch includes [googkit.cmd](https://github.com/cocopon/googkit/blob/win_support/bin/googkit.cmd) for the Windows Command Prompt.

Do you agree to merge the branch? Now, this branch is not merged to the master because supporting Windows is hard to us.

**Comment by cocopon** [comment]
Please merge the branch.
(I don't have Windows, but) we should support the mainstream operating system.

**Comment by Kuniwak** [comment]
OK, I merged [win_support](https://github.com/cocopon/googkit/tree/win_support).
